feat:
  center_crop: !!python/tuple
  - true
  - 910
  - 910
  feature_type: dinov2
  input_size: 1078
  interp: bilinear
  physical_dim: 2
  resize: true
  segmentation_type: pixel
general:
  model_path: model
  name: debug/debug
  online_training: false
  plot_overlay_online: true
  resume_training: true
  resume_training_path: model/last_checkpoint_hiking.pt
  timestamp: true
graph:
  cut_threshold: 5.0
  edge_dist_thr_main_graph: 1
  edge_dist_thr_sub_graph: 0.2
  extraction_store_folder: LabelExtraction
  label_ext_mode: false
  max_distance_sub_graph: 5
  min_samples_for_training: 6
  random_sample_num: 100
  update_range_main_graph: 5
  update_range_sub_graph: 5
  use_for_training: true
  use_sub_graph: true
  vis_node_index: 10
logger:
  name: neptune
  neptune_project_name: RSL/WVN
  vis_callback: true
  vis_mgraph: true
  vis_snodes: true
loss:
  confidence_mode: gmm_1d
  confidence_std_factor: 1.0
  confidence_threshold: 0.5
  log_enabled: false
  log_folder: /tmp
  method: running_mean
  verbose: true
  w_pred: 0.5
  w_reco: 0.5
model:
  load_ckpt: null
  name: SimpleMLP
  rnd_mlp_cfg:
    hidden_sizes_pred:
    - 128
    - 32
    hidden_sizes_target:
    - 128
    - 32
    input_size: 384
    pred_head: 2
  seperate_mlp_cfg:
    hidden_sizes:
    - 256
    - 64
    - 256
    - 2
    input_size: 384
  seprnd_mlp_cfg:
    hidden_sizes_pred:
    - 256
    - 64
    hidden_sizes_target:
    - 256
    - 64
    input_size: 384
    pred_head: 2
  simple_mlp_cfg:
    hidden_sizes:
    - 128
    - 32
    - 128
    - 2
    input_size: 384
    reconstruction: true
offline:
  SAM_ckpt: /media/chen/UDisk1/sam_vit_h_4b8939.pth
  SAM_type: vit_h
  ckpt_parent_folder: results/overlay
  data_folder: results/manager
  gt_model: SAM
  image_file: image_buffer.pt
  mode: test
  nodes_data: results/manager/train_nodes.pt
  plot_hist: false
  plot_masks_compare: false
  plot_nodes: false
  plot_overlay: true
  plot_tsne: false
  test_images: false
  test_nodes: true
  train_data: results/manager/train_data.pt
  use_online_ckpt: true
optimizer:
  lr: 0.001
  name: ADAM
roscfg:
  anymal_bag_name: lpc
  anymal_state_topic: /state_estimator/anymal_state
  base_frame: base
  camera_bag_name: jetson
  camera_info_topic: /wide_angle_camera_rear/camera_info
  camera_topic: /wide_angle_camera_rear/image_color_rect/compressed
  feet_list:
  - LF_FOOT
  - RF_FOOT
  - LH_FOOT
  - RH_FOOT
  fixed_frame: odom
  foot_radius: 0.03269
  footprint_frame: footprint
  phy_decoder_input_topic: /debug_info
  phy_decoder_output_topic: /vd_pipeline/phy_decoder_out
  robot_height: 0.89
  robot_length: 0.93
  robot_max_velocity: 1.2
  robot_width: 0.53
run:
  device: cuda
  mode: debug
  palette: husl
  print_time: true
thread:
  image_callback_rate: 1.0
  learning_rate: 0.5
  logging_rate: 0.5
  proprio_callback_rate: 4.0
