camera_topics:
  front:
    image_topic: "/usb_cam/image_raw"
    info_topic: "/usb_cam/camera_info"
    use_for_training: false
    publish_confidence: true
    publish_input_image: true
    scheduler_weight: 1
  # rear:
  #   image_topic: "/wide_angle_camera_rear/image_color_rect_resize"
  #   info_topic: "/wide_angle_camera_rear_resize/camera_info"
  #   use_for_training: true
  #   publish_confidence: true
  #   publish_input_image: true
  #   scheduler_weight: 1
  
# Provides 1080 (height) x 1920 (width) images
network_input_image_height: 480 # 224 # 448
network_input_image_width: 640 # 224 # 448