grid_map_filters:

  - name: buffer_normalizer
    type: gridMapFilters/BufferNormalizerFilter
  
  # Nan Mask
  - name: nan_mask
    type: gridMapFiltersDrs/NanMaskFilter
    params:
      input_layer: elevation
      output_layer: unknown_space

  # Inpainting
  - name: denoise_inpaint
    type: gridMapFiltersDrs/DenoiseAndInpaintFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted
      radius: 0.1 # in m
      inpainting_type: telea # 'ns' or 'telea' allowed
      pre_denoising: false # enables denoising before inpainting
      denoising_radius: 0.5 # m
      denoising_type: non_local # 'total_variation', 'non_local', 'gaussian', and 'median' supported
      total_variation_lambda: 1.0

  #=====================================================================
  # Geometric traversability
  #=====================================================================
  # Compute surface normals (fast)
  - name: surface_normals
    type: gridMapFiltersDrs/FastNormalsVectorFilter
    params:
      input_layer: elevation_inpainted
      output_layers_prefix: normal_
      use_pre_smoothing: true
      use_post_smoothing: true
      pre_smoothing_radius: 0.15 # spatial gaussian filter (in meters)
      post_smoothing_radius: 0.1 # spatial median filter (in meters)

  # Compute slope from surface normal.
  - name: slope
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: slope
      expression: acos(normal_z)
  
  # Compute base threshold
  - name: height_filter
    type: gridMapFiltersDrs/BaseHeightThresholdFilter
    params:
      input_layer: elevation_inpainted
      output_layer: height_traversability
      target_frame: base
      threshold: -0.3
      set_to_upper: 0.0
      set_to_lower: 1.0

  # Compute traversability as normalized weighted sum of slope and roughness.
  - name: traversability
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: geometric_traversability
      expression: (0.5 * (1.0 - (slope / 0.6)) + 0.5 * height_traversability)

  # Compute 2D Signed Distance Field
  - name: geometric_sdf
    type: gridMapFiltersDrs/SignedDistanceField2dFilter
    params:
      input_layer: geometric_traversability
      output_layer: geometric_sdf
      normalize_gradients: true
      threshold: 0.1

  #=====================================================================
  # Geometric learned traversability
  #=====================================================================
  # Inpaint visual traversability
  - name: geometric_learned_traversability_inpaint
    type: gridMapFiltersDrs/DenoiseAndInpaintFilter
    params:
      input_layer: traversability
      output_layer: geometric_learned_traversability
      radius: 0.1 # in m
      inpainting_type: telea # 'ns' or 'telea' allowed
      pre_denoising: true # enables denoising before inpainting
      denoising_radius: 0.12 # m
      denoising_type: median # 'total_variation', 'non_local', 'gaussian', and 'median' supported
      total_variation_lambda: 1.0
  
  # Compute 2D Signed Distance Field
  - name: geometric_learned_sdf
    type: gridMapFiltersDrs/SignedDistanceField2dFilter
    params:
      input_layer: geometric_learned_traversability
      output_layer: geometric_learned_sdf
      normalize_gradients: true
      threshold: 0.1

  #=====================================================================
  # Visual traversability
  #=====================================================================
  - name: footprint_mask
    type: gridMapFiltersDrs/FootprintMaskFilter
    params:
      output_layer: footprint_mask
      footprint_frame: base
      type: rectangle
      length: 1.0
      width: 0.5
      clearance: 0.1

  # Inpaint visual traversability
  - name: inpaint_visual_traversability
    type: gridMapFiltersDrs/DenoiseAndInpaintFilter
    params:
      input_layer: visual_traversability
      output_layer: visual_traversability_inpainted
      radius: 0.1 # in m
      inpainting_type: telea # 'ns' or 'telea' allowed
      pre_denoising: true # enables denoising before inpainting
      denoising_radius: 0.12 # m
      denoising_type: median # 'total_variation', 'non_local', 'gaussian', and 'median' supported
      total_variation_lambda: 1.0
  
  - name: visual_traversability_footprint_fix
    type: gridMapFilters/MathExpressionFilter
    params:
      output_layer: visual_traversability_inpainted
      expression: (1.0 - footprint_mask) .* visual_traversability_inpainted + footprint_mask
  
  # Compute 2D Signed Distance Field
  - name: visual_sdf
    type: gridMapFiltersDrs/SignedDistanceField2dFilter
    params:
      input_layer: visual_traversability_inpainted
      output_layer: visual_sdf
      normalize_gradients: true
      threshold: 0.1
