grid_map_filters:

  - name: delete
    type: gridMapFiltersDrs/DeleteAllButFilter
    params:
      layers: [elevation, elevation_inpainted, geometric_traversability, geometric_learned_traversability, visual_traversability_inpainted, geometric_sdf, geometric_learned_sdf, visual_sdf] # List of layers.